module.exports = [
  { name: "Rahul Patil", email: "rahul@gmail.com" },
  { name: "Ganesh Bhosale", email: "ganesh@gmail.com" },
  { name: "Amit Jadhav", email: "amit@gmail.com" },
  { name: "Rohan Shinde", email: "rohan@gmail.com" },
  { name: "Sanket More", email: "sanket@gmail.com" },
  { name: "Sneha Pawar", email: "sneha@gmail.com" },
  { name: "Priya Sharma", email: "priya@gmail.com" },
  { name: "Pooja Patil", email: "pooja@gmail.com" },
  { name: "Neha Kulkarni", email: "neha@gmail.com" },
  { name: "Vaishnavi Kale", email: "vaishnavi@gmail.com" },

  { name: "Akash Patil", email: "akash@gmail.com" },
  { name: "Nikhil Jagtap", email: "nikhil@gmail.com" },
  { name: "Tejas Shinde", email: "tejas@gmail.com" },
  { name: "Kunal More", email: "kunal@gmail.com" },
  { name: "Pratik Chavan", email: "pratik@gmail.com" },
  { name: "Komal Pawar", email: "komal@gmail.com" },
  { name: "Rutuja Patil", email: "rutuja@gmail.com" },
  { name: "Sakshi Jadhav", email: "sakshi@gmail.com" },
  { name: "Anjali Kale", email: "anjali@gmail.com" },
  { name: "Monika Deshmukh", email: "monika@gmail.com" },
    { name: "Abhishek Kulkarni", email: "abhishek@gmail.com" },
  { name: "Sagar Pawar", email: "sagar@gmail.com" },
  { name: "Vishal Jadhav", email: "vishal@gmail.com" },
  { name: "Aditya Patil", email: "aditya@gmail.com" },
  { name: "Yash More", email: "yash@gmail.com" },
  { name: "Omkar Shinde", email: "omkar@gmail.com" },
  { name: "Harshal Chavan", email: "harshal@gmail.com" },
  { name: "Suraj Bhosale", email: "suraj@gmail.com" },
  { name: "Nilesh Kale", email: "nilesh@gmail.com" },
  { name: "Swapnil Patil", email: "swapnil@gmail.com" },

  { name: "Kiran Deshmukh", email: "kiran@gmail.com" },
  { name: "Shubham Jagtap", email: "shubham@gmail.com" },
  { name: "Rakesh Mane", email: "rakesh@gmail.com" },
  { name: "Ajinkya Patil", email: "ajinkya@gmail.com" },
  { name: "Bhavesh More", email: "bhavesh@gmail.com" },
  { name: "Aarti Patil", email: "aarti@gmail.com" },
  { name: "Pallavi Shinde", email: "pallavi@gmail.com" },
  { name: "Kajal More", email: "kajal@gmail.com" },
  { name: "Madhuri Jadhav", email: "madhuri@gmail.com" },
  { name: "Priti Kulkarni", email: "priti@gmail.com" },
    { name: "Aniket Patil", email: "aniket@gmail.com" },
  { name: "Saurabh Jadhav", email: "saurabh@gmail.com" },
  { name: "Rohit Gavali", email: "rohit@gmail.com" },
  { name: "Prasad More", email: "prasad@gmail.com" },
  { name: "Mahesh Shinde", email: "mahesh@gmail.com" },
  { name: "Vikas Chavan", email: "vikas@gmail.com" },
  { name: "Akshay Pawar", email: "akshay@gmail.com" },
  { name: "Chetan Patil", email: "chetan@gmail.com" },
  { name: "Deepak Kale", email: "deepak@gmail.com" },
  { name: "Ruturaj Bhosale", email: "ruturaj@gmail.com" },

  { name: "Sonali Patil", email: "sonali@gmail.com" },
  { name: "Pallavi Deshmukh", email: "pallavid@gmail.com" },
  { name: "Shraddha More", email: "shraddha@gmail.com" },
  { name: "Reshma Patil", email: "reshma@gmail.com" },
  { name: "Dipali Jadhav", email: "dipali@gmail.com" },
  { name: "Prajakta Shinde", email: "prajakta@gmail.com" },
  { name: "Ashwini Kale", email: "ashwini@gmail.com" },
  { name: "Bhagyashree Patil", email: "bhagyashree@gmail.com" },
  { name: "Sonal Chavan", email: "sonal@gmail.com" },
  { name: "Manisha More", email: "manisha@gmail.com" },

];